Repository ryo-currency/ryo-currency, pull requests merged in 2018-07, with the labels that each got.

#25 Use boost for aligned alloc
  src/crypto/cn_slow_hash.hpp
Labels: enhancement

#29 fix clang compile
  src/CMakeLists.txt
  src/blockchain_utilities/CMakeLists.txt
  src/cryptonote_config.cpp
  src/daemon/CMakeLists.txt
  src/mnemonics/electrum-words.cpp
  src/simplewallet/CMakeLists.txt
  src/wallet/CMakeLists.txt
  tests/core_proxy/CMakeLists.txt
  tests/core_tests/CMakeLists.txt
  tests/unit_tests/CMakeLists.txt
Labels: bug

#37 take care that blockchain is not read only available
  src/cryptonote_core/blockchain.cpp
Labels: enhancement

#35 fix address file is not created
  src/simplewallet/simplewallet.cpp
Labels: bug

#39 is_ready fix
  src/rpc/core_rpc_server.cpp
Labels: bug

#38 fix tx double scan
  src/wallet/wallet2.cpp
Labels: bug

#45 fix travis tests
  .travis.yml
Labels: bug

#46 Implement stricter tx semantics
  src/cryptonote_config.h
  src/cryptonote_core/blockchain.cpp
Labels: enhancement

#48 fix a bug in rescan_bc
  src/wallet/wallet2.cpp
Labels: bug

#47 fix `get_approximate_blockchain_height`
  src/wallet/wallet2.cpp
Labels: bug

#51 Prompt if daemon-address is incomplete
  contrib/epee/include/net/http_client.h
  src/simplewallet/simplewallet.cpp
  src/simplewallet/simplewallet.h
  src/wallet/wallet2.cpp
Labels: enhancement

#50 simplewallet: `rescan_bc` add optional argument
  src/simplewallet/simplewallet.cpp
  src/simplewallet/simplewallet.h
  src/wallet/wallet2.cpp
Labels: enhancement

#58 fix ryo units
  src/cryptonote_basic/cryptonote_format_utils.cpp
  src/simplewallet/simplewallet.cpp
Labels: bug

#59 fix invalid block data usage
  src/cryptonote_core/blockchain.cpp
Labels: bug

#60 Clean up and add a no pub key check
  src/cryptonote_core/blockchain.cpp
Labels: enhancement

#62 Minor fixes
  src/checkpoints/checkpoints.cpp
  src/cryptonote_config.h
  src/cryptonote_core/blockchain.cpp
  src/cryptonote_core/cryptonote_tx_utils.cpp
Labels: bug

#63 Topic fee increase
  src/cryptonote_config.h
  src/cryptonote_core/blockchain.cpp
  src/cryptonote_core/blockchain.h
  src/cryptonote_core/tx_pool.cpp
  src/daemon/rpc_command_executor.cpp
  src/rpc/core_rpc_server.cpp
  src/rpc/core_rpc_server.h
  src/rpc/core_rpc_server_commands_defs.h
  src/rpc/daemon_handler.cpp
  src/rpc/daemon_handler.h
  src/rpc/daemon_messages.cpp
  src/rpc/daemon_messages.h
  src/simplewallet/simplewallet.cpp
  src/simplewallet/simplewallet.h
  src/wallet/api/wallet.cpp
  src/wallet/api/wallet.h
  src/wallet/api/wallet2_api.h
  src/wallet/node_rpc_proxy.cpp
  src/wallet/node_rpc_proxy.h
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server.h
  src/wallet/wallet_rpc_server_commands_defs.h
Labels: refactoring
