Repository ryo-currency/ryo-currency, pull requests merged in 2018-10, with the labels that each got.

#132 dns_utils: refresh list of usable DNSSEC servers
  src/common/dns_utils.cpp
Labels: refactoring

#131 dns_util: add new DNSSEC trust anchor for rollover
  src/common/dns_utils.cpp
Labels: refactoring

#129 fix faild subaddress sanity check
  src/wallet/wallet2.cpp
Labels: bug

#138 Implement wallet restore from viewkey on RPC
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server.h
  src/wallet/wallet_rpc_server_commands_defs.h
Labels: enhancement

#136 fix wrong unit names
  src/simplewallet/simplewallet.cpp
  src/wallet/wallet2.cpp
  tests/unit_tests/canonical_amounts.cpp
  translations/ryo.ts
  translations/ryo_fr.ts
  translations/ryo_it.ts
  translations/ryo_sv.ts
Labels: bug

#139 wallet_rpc: keyimg is now binary
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server_commands_defs.h
Labels: refactoring
