Repository ryo-currency/ryo-currency, pull requests merged in 2018-08, with the labels that each got.

#67 fix readline support for docker
  Dockerfile
Labels: bug

#73 fix unittest base58
  tests/unit_tests/base58.cpp
Labels: bug

#75 fix tests for block reward
  src/cryptonote_config.h
  tests/unit_tests/block_reward.cpp
Labels: bug

#80 increase minimal CMake version to 3.1.0
  CMakeLists.txt
  src/cryptonote_protocol/CMakeLists.txt
  src/p2p/CMakeLists.txt
Labels: refactoring

#72 remove address from DNS txt record
  src/common/dns_utils.cpp
  src/common/dns_utils.h
  src/cryptonote_basic/cryptonote_basic_impl.cpp
  src/cryptonote_basic/cryptonote_basic_impl.h
  src/daemon/command_parser_executor.cpp
  src/simplewallet/simplewallet.cpp
  src/wallet/api/wallet2_api.h
  src/wallet/api/wallet_manager.cpp
  src/wallet/api/wallet_manager.h
  src/wallet/wallet_rpc_server.cpp
  tests/fuzz/signature.cpp
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/address_from_url.cpp
Labels: refactoring

#81 CMake rename `monero_add_library`
  src/CMakeLists.txt
  src/blockchain_db/CMakeLists.txt
  src/checkpoints/CMakeLists.txt
  src/common/CMakeLists.txt
  src/crypto/CMakeLists.txt
  src/cryptonote_basic/CMakeLists.txt
  src/cryptonote_core/CMakeLists.txt
  src/cryptonote_protocol/CMakeLists.txt
  src/daemonizer/CMakeLists.txt
  src/device/CMakeLists.txt
  src/mnemonics/CMakeLists.txt
  src/multisig/CMakeLists.txt
  src/p2p/CMakeLists.txt
  src/ringct/CMakeLists.txt
  src/rpc/CMakeLists.txt
  src/serialization/CMakeLists.txt
  src/wallet/CMakeLists.txt
  src/wallet/api/CMakeLists.txt
Labels: refactoring

#82 Mnemomnic language cleanup
  src/blockchain_utilities/CMakeLists.txt
  src/common/boost_locale.hpp
  src/gen_multisig/CMakeLists.txt
  src/mnemonics/electrum-words.cpp
  src/mnemonics/electrum-words.h
  src/mnemonics/russian.h
  src/simplewallet/CMakeLists.txt
  src/simplewallet/simplewallet.cpp
  src/simplewallet/simplewallet.h
  src/wallet/CMakeLists.txt
  src/wallet/wallet_rpc_server.cpp
Labels: enhancement, refactoring

#87 fix URI parsing
  src/wallet/wallet2.cpp
Labels: bug

#86 Monero caching bug
  src/cryptonote_basic/hardfork.cpp
  src/cryptonote_basic/hardfork.h
  src/cryptonote_core/blockchain.h
  src/wallet/node_rpc_proxy.cpp
  src/wallet/wallet2.cpp
Labels: bug

#85 restore_wallet rpc
  .gitignore
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server.h
  src/wallet/wallet_rpc_server_commands_defs.h
Labels: enhancement

#89 extent travis CI tests
  .travis.yml
  tests/core_tests/CMakeLists.txt
  tests/difficulty/CMakeLists.txt
Labels: refactoring, tests

#90 fix wrong exit code for `--help`
  src/blockchain_utilities/blockchain_blackball.cpp
  src/blockchain_utilities/blockchain_export.cpp
  src/blockchain_utilities/blockchain_import.cpp
  src/blockchain_utilities/blockchain_usage.cpp
  src/debug_utilities/cn_deserialize.cpp
  src/gen_multisig/gen_multisig.cpp
  src/simplewallet/simplewallet.cpp
  src/wallet/wallet_args.cpp
  src/wallet/wallet_args.h
  src/wallet/wallet_rpc_server.cpp
Labels: bug

#94 Wallet fixes
  src/crypto/crypto.cpp
  src/simplewallet/simplewallet.cpp
  src/simplewallet/simplewallet.h
Labels: bug

#93 fix broken travis tests
  .travis.yml
  tests/gtest/CMakeLists.txt
Labels: bug, tests

#98 fix CryptGenRandom return val
  src/crypto/random.cpp
Labels: bug

#101 fix gcc8 compile under linux
  .travis.yml
  src/cryptonote_basic/account.cpp
  src/daemon/rpc_command_executor.cpp
  src/rpc/core_rpc_server_commands_defs.h
Labels: bug

#100 fix possible infinite loop in `tx_pool`
  src/cryptonote_core/tx_pool.cpp
Labels: bug

#103 simplewallet: fix unspend output
  src/simplewallet/simplewallet.cpp
Labels: bug

#104 Wallet: fix division by zero
  src/wallet/wallet2.cpp
Labels: bug

#99 Windows Internationalization Fixes
  src/wallet/CMakeLists.txt
  src/wallet/wallet_args.cpp
Labels: bug

#102 Implement Windows Unicode APIs
  src/address_validator/address_validator.cpp
  src/blockchain_utilities/blockchain_blackball.cpp
  src/blockchain_utilities/blockchain_export.cpp
  src/blockchain_utilities/blockchain_import.cpp
  src/blockchain_utilities/blockchain_usage.cpp
  src/common/command_line.cpp
  src/common/command_line.h
  src/daemon/main.cpp
  src/daemonizer/daemonizer.h
  src/daemonizer/posix_daemonizer.inl
  src/daemonizer/windows_daemonizer.inl
  src/gen_multisig/gen_multisig.cpp
  src/simplewallet/simplewallet.cpp
  src/wallet/wallet_rpc_server.cpp
Labels: bug

#96 Optimise hashes
  src/crypto/CMakeLists.txt
  src/crypto/aux_hash.c
  src/crypto/aux_hash.h
  src/crypto/blake256.c
  src/crypto/blake256.h
  src/crypto/cn_slow_hash_hard_arm.cpp
  src/crypto/cn_slow_hash_hard_intel.cpp
  src/crypto/cn_slow_hash_soft.cpp
  src/crypto/groestl.c
  src/crypto/groestl.h
  src/crypto/groestl_tables.h
  src/crypto/hash-extra-groestl.c
  src/crypto/hash-extra-jh.c
  src/crypto/hash-extra-skein.c
  src/crypto/hash-ops.h
  src/crypto/jh.c
  src/crypto/jh.h
  src/crypto/skein.c
  src/crypto/skein.h
  src/crypto/skein_port.h
  tests/hash/main.cpp
  tests/hash/tests-extra-blake.txt
  tests/hash/tests-extra-groestl.txt
  tests/hash/tests-extra-jh.txt
  tests/hash/tests-extra-skein.txt
Labels: refactoring

#105 Use zram instead of swap for the Raspberry Pi
  README.md
Labels: enhancement

#106 Open wallet on restore
  src/wallet/wallet_rpc_server.cpp
Labels: bug

#107 Add close wallet rpc call
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server.h
  src/wallet/wallet_rpc_server_commands_defs.h
Labels: enhancement
