Repository ryo-currency/ryo-currency, pull requests merged in 2019-02, with the labels that each got.

#173 Remove OptimizeCoinbase refresh
  src/simplewallet/simplewallet.cpp
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
Labels: refactoring

#181 fix CI
  .travis.yml
Labels: bug

#182 Multisig fix
  src/cryptonote_basic/cryptonote_format_utils.cpp
  src/cryptonote_basic/cryptonote_format_utils.h
  src/cryptonote_core/cryptonote_tx_utils.cpp
  src/cryptonote_core/cryptonote_tx_utils.h
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
  tests/performance_tests/check_tx_signature.h
  tests/performance_tests/construct_tx.h
  tests/performance_tests/ge_frombytes_vartime.h
  tests/performance_tests/ge_tobytes.h
  tests/unit_tests/json_serialization.cpp
Labels: bug

#183 Increase to v0.4.0.1
  src/version.cpp.in
Labels: documentation

#184 libunbound: fix MinGW compile
  external/unbound/configure_checks.cmake
Labels: bug

#187 7zip key images
  utils/burned_premine_keyimages/key_images.7z
  utils/burned_premine_keyimages/wallet-dev_key_images.bin
  utils/burned_premine_keyimages/wallet1_key_images.bin
  utils/burned_premine_keyimages/wallet2_key_images.bin
  utils/burned_premine_keyimages/wallet3_key_images.bin
Labels: bug

#189 Create verify_premine_burn_instructions.md
  README.md
  utils/burned_premine_keyimages/verify_premine_burn_instructions.md
Labels: documentation
