Repository ryo-currency/ryo-currency, pull requests merged in 2019-08, with the labels that each got.

#209 fix boost version check in CMake
  CMakeLists.txt
Labels: bug

#210 fix cmake (broken windows compile)
  CMakeLists.txt
Labels: bug

#215 Fix build for maos
  contrib/epee/include/net/abstract_tcp_server2.inl
Labels: bug

#211 fix usage of depricated boost functions/defines
  contrib/epee/include/math_helper.h
  external/boost/archive/portable_binary_archive.hpp
  external/boost/archive/portable_binary_iarchive.hpp
  external/boost/archive/portable_binary_oarchive.hpp
Labels: warning

#216 optimze queue lock handling
  src/common/gulps.hpp
  src/common/thdq.hpp
  src/wallet/wallet2.cpp
  src/wallet/wallet2_tx_scan.cpp
Labels: refactoring

#217 fix alt chain coin overflow
  src/cryptonote_core/blockchain.cpp
Labels: bug
