Repository ryo-currency/ryo-currency, pull requests merged in 2019-05, with the labels that each got.

#192 Add verbage to the readme to outline the process for importing blockchain data from a file
  README.md
Labels: documentation

#195 boost 1.7.0 fixes
  .travis.yml
  CMakeLists.txt
  contrib/epee/include/net/abstract_tcp_server2.inl
  contrib/epee/include/net/net_utils_base.h
  src/simplewallet/simplewallet.cpp
  src/wallet/wallet_args.cpp
Labels: bug

#193 Add a save-wallets script
  utils/load-wallets.sh
  utils/save-wallets.sh
Labels: enhancement

#196 libreadline fix on msys2
  contrib/epee/src/CMakeLists.txt
Labels: bug
